language: node_js
node_js:
- lts/*  # Most recent LTS version, i.e. 12 in August, 2020
- 10
sudo: required
addons:
  chrome: stable
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libavformat-dev libavfilter-dev libavdevice-dev ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
install:
- npm install
script:
- npm run test
